### PR TITLE
Rename Beggar to PesteR

### PR DESCRIPTION
**Pull request by calebthompson**
pes·ter
    /ˈpestər/
    _verb_

    trouble or annoy (someone) with frequent or persistent requests or
    interruptions.

    synonyms: badger, hound, harass, plague, annoy, bother, trouble,
             keep after, persecute, torment, bedevil, harry, worry,
             beleaguer, nag, hassle, bug, devil, get on someone's case

    > "is there someplace I can study where no one will pester me?"

Besides the obvious wordplay, PesteR doesn't invoke the idea of someone begging
for help and rather suggests that we're being bothered.

This is more in line with how we consider, for example, Hound: a service to be
annoying about things like style so that nobody has to be 'that person'
troubling coworkers. PesteR pings regularly to remind us to review our friends
PRs so that they can tighten the feedback cycle and we don't forget.

### CODE REVIEW

**Comment by calebthompson** [comment]
Code Climate failure is for the rename from PrTool => Pester and doesn't actually represent any new complexity. I don't think we've ever bothered to try to simplify configuration files.

**Comment by drapergeek** [comment]
Needs a new icon and the current icon file needs to be renamed.

**Comment by calebthompson** [comment]
Looks like the logo.svg isn't being used. Maybe it should be deleted?

**Comment by calebthompson** [comment]
image

Thoughts?

**Comment by drapergeek** [comment]
I liked the one that was less "happy" personally but I'm not picky.

**Comment by drapergeek** [comment]
>Looks like the logo.svg isn't being used. Maybe it should be deleted?
Sure

**Comment by calebthompson** [comment]
image

**Comment by drapergeek** [comment]
If all is well, merge at will @calebthompson. Feel free to change the repo name whenever it is merged.

**Pull request merged**
